encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"

urlpatterns = [
    path("", views.index, name="index"),
    path("add/", views.add, name="add"),
    path("edit/", views.edit, name="edit"),
    path("entry/", views.entry, name="entry"),
    path("random/", views.random, name="random"),
    path("save_edit", views.save_edit, name="save_edit"),
    path("search/", views.search, name="search"),
    path("wiki/<str:q>", views.wiki, name="wiki")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
    
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.contrib import messages
from markdown2 import Markdown
from random import choice
from . import util


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
    })


def add(request): 
    if request.method == "POST":
            title = request.POST["title"]
            content = request.POST["content"]
            
            if util.get_entry(title):
                return render(request, "encyclopedia/error.html", {
                    "message": "Entry already in database"
                })
            
            else:
                util.save_entry(title, content)
                messages.success(request, "Entry added!")
                markdowner = Markdown()
                return render(request, "encyclopedia/entry.html", {
                    "title": title,
                    "content": markdowner.convert(content)
                })
        
    else:
        return render(request, "encyclopedia/add.html")


def entry(request, q):
    content = util.get_entry(q)
    markdowner = Markdown()
    return render(request, "encyclopedia/entry.html", {
        "title": q,
        "content": markdowner.convert(content)
    })


def random(request):
    entry = choice(util.list_entries())
    content = util.get_entry(entry)
    markdowner = Markdown()

    return render(request, "encyclopedia/entry.html", {
        "title": entry,
        "content": markdowner.convert(content)
    })


def search(request):
    if request.method == "POST":
        q = request.POST["q"]
        
        try:
            content = util.get_entry(q)
            markdowner = Markdown()
            html = markdowner.convert(content)

            if html:
                return render(request, "encyclopedia/entry.html", {
                "title": q,
                "content": html 
                })
            
        except TypeError:
            entries = util.list_entries()
            matches = []
            for entry in entries:
                if q in entry:
                    matches.append(entry)
            
            if not matches:
                return render(request, "encyclopedia/error.html", {
                    "message": "No matches found"
                })
            
            return render(request, "encyclopedia/search.html", {
            "matches": matches
            })


def wiki(request, q):
    content = util.get_entry(q)
    
    if content:
        markdowner = Markdown()
      
        return render(request, "encyclopedia/q.html", {
           "title": q, 
           "content": markdowner.convert(content)
        })

    else:
        return render(request, "encyclopedia/error.html", {
            "message": "Entry not found"
        })
    

def error(request, message):
    return render(request, "encyclopedia/error.html", {
        "message": message
    })

def edit(request):
    if request.method == "POST":
        title = request.POST["title"]
        content = util.get_entry(title)

        return render(request, "encyclopedia/edit.html", {
            "title": title,
            "content": content
        })
        
def save_edit(request):
    if request.method == "POST":
        title = request.POST["title"]
        edit = request.POST["edit"]

        util.save_entry(title, edit)
        markdowner = Markdown()

        return render(request, "encyclopedia/entry.html", {
            "title": title,
            "content": markdowner.convert(edit)
        })

   

encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Add an Entry
{% endblock %}

{% block body %}
    <h1 style="text-align: center;">Add an entry!</h1>

        <form action="{% url 'wiki:add' %}" method="POST">
            {% csrf_token %}
            <label>Entry name:</label>
            <input type="text" name="title" placeholder="Entry title"> 
            <label>Entry content:</label>
            <textarea name="content"></textarea>
            <button type="submit">Submit</button>
        </form>


{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit
{% endblock %}

{% block body %}
    
    <h1 style="text-align: center;">Edit an entry!</h1>

        <form action="{% url 'wiki:save_edit' %}" method="POST">
            {% csrf_token %}
            <label>New entry content:</label>
            <input type="hidden" name="title" value="{{ title }}">
            <textarea name="edit">{{ content }}</textarea>
            <button type="submit">Submit</button>
        </form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}

    {{ title|safe }}

{% endblock %}

{% block body %}

    {{ content|safe }}
    <br>
    <form action="{% url 'wiki:edit' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="title" value="{{ title }}">
        <button type="submit">Edit</button>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
  
    <h1>Error</h1>
    {{ message}}

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
        <li><a href="wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search' %}" method="POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    
                    <a href="{% url 'wiki:add' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Title
{% endblock %}

{% block body %}
    

{% endblock %}

encyclopedia/templates/encyclopedia/q.html
{% extends "encyclopedia/layout.html" %}

{% block title %}

    {{ title|safe }}

{% endblock %}

{% block body %}

    {{ content|safe }}
    <br>
    <form action="{% url 'wiki:edit' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="title" value="{{ title }}">
        <button type="submit">Edit</button>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search
{% endblock %}

{% block body %}

<h1>Did you mean:</h1>

<ul>
{% for match in matches %}

<li><a href="{% url 'wiki:wiki' q=match %}">{{ match }}</a></li>

{% endfor %}
</ul>

{% endblock %}